added  some common header values
mfinelli/cui pull request #14
Opened 2022-10-24 09:40 UTC by DataKhukhua

I tried to replicate what you've done on header keys , and it works  . 
P.S first time contributing to open source  🫡

2022-10-24 12:26 UTC, mfinelli requested changes
Hi, thanks for contributing! I've left a couple of minor comments. Cheers!

2022-10-24 12:26 UTC, mfinelli commented on main.go
> +	cui.RequestHeaderValue.SetAutocompleteFunc(func(currentText string) (entries []string) {
We only want this autocomplete to run if the header key is `Content-Type`, so at the beginning of this function you should add a guard like so:

```go
if !strings.EqualFold("Content-Type", cui.RequestHeaderKey.GetText()) {
        return
}
```

2022-10-24 12:26 UTC, mfinelli commented on words.go
> +var commonHeaderValues = []string{
Could you please name this `commonHeaderContentTypes` or similar? I think we'll probably add other common value autocompletes in the future.

2022-10-24 12:27 UTC, mfinelli commented
Resolves #5

2022-10-24 13:00 UTC, DataKhukhua commented on words.go
> +var commonHeaderValues = []string{
I will change it  asap 🤠

2022-10-24 13:01 UTC, DataKhukhua commented on words.go
> +var commonHeaderValues = []string{
I will change it  asap 🤠

2022-10-25 06:51 UTC, mfinelli requested changes

2022-10-25 06:51 UTC, mfinelli commented on words.go
> +var commonHeaderContentTypes = []string{
Sorry, one more minor thing. Can you please alphabetize this list and remove `application/zip`? It seems unlikely that someone will be able to enter a proper zip payload into the text area. Thanks

2022-10-25 06:57 UTC, DataKhukhua commented on words.go
> +var commonHeaderContentTypes = []string{
Yes , of course . Thanks for feedback 🫡

2022-10-25 12:18 UTC, mfinelli approved these changes

2022-10-25 12:29 UTC, closed without merging

2022-10-25 12:30 UTC, mfinelli commented
This says closed, but I squashed and merged it. Thanks again for contributing!