Feature  save response
mfinelli/cui pull request #16
Opened 2022-10-27 10:53 UTC by DataKhukhua

Implemented save responseBody in file feature  , replace file if already exists not implemented yet , but it can detect when given filename is already in filesystem .

2022-10-28 12:58 UTC, mfinelli commented
Thanks, this generally looks pretty good, I'll be able to do a better review this weekend. Cheers

2022-10-28 13:03 UTC, DataKhukhua commented
okay , I will implement replace  function on weekend too .

2022-10-31 20:45 UTC, DataKhukhua commented
Added Replace Function  @mfinelli

2022-11-05 16:11 UTC, mfinelli requested changes

2022-11-05 16:11 UTC, mfinelli commented on main.go
> +				err := ReplaceSaveResponseFile(filePath, responseBody)
Can you pass the `cui` object here and then pull the response body out inside the save response function?

2022-11-05 16:11 UTC, mfinelli commented on save_response.go
> +		return os.ErrExist
Is there a specific reason that are you returning `os.ErrExist` here? AFAIK this can error for other reasons as well, I think it's better to just return whatever error we get and then check specifically in the caller (which you're already doing correctly) if it's an ErrExist to prompt the user to overwrite.

2022-11-05 16:11 UTC, mfinelli commented on save_response.go
> +func ReplaceSaveResponseFile(filePath string, responseBody string) error {
Thus function is mostly the same as the other one, I think that you could just add a "truncate" parameter to pass in which case you add the o_TRUNC option if set or return an ErrExist if not in order to reduce code duplication. What do you think?

2022-11-05 16:12 UTC, mfinelli commented
@DataKhukhua sorry for the slow review here, I left a couple of minor comments, if you could address them I'll get this merged in and then cut a new release. Cheers!

2022-11-07 10:13 UTC, DataKhukhua commented on save_response.go
> +		return os.ErrExist
Hi, os.Stat function returns  nil as error, if there is an existing file , this is why I return ErrExist error .

2022-11-07 10:16 UTC, DataKhukhua commented on save_response.go
> +func ReplaceSaveResponseFile(filePath string, responseBody string) error {
I thought that too , that  there was a  code duplication , but I think this is more readable . I will change it to one function no problem .

2022-11-09 19:08 UTC, mfinelli commented on save_response.go
> +		return os.ErrExist
Ok, I see. Let's instead create a function to make this easier to reason about, something like:

```go
func FileExists(path string) (bool, error) {
        if _, err := os.Stat("/path/to/whatever"); err == nil {
                return true, nil
        } else if errors.Is(err, os.ErrNotExist) {
                return false, nil
        } else {
                return true, err // or false, doesn't matter
        }
}
```

This way you can then do a normal check of filexists with the path, if you get an error then abort completely, otherwise you can do the normal decision based on the file existence (namely ask to overwrite or not).

What do you think?

2022-11-10 07:13 UTC, DataKhukhua commented on save_response.go
> +		return os.ErrExist
Okay , it makes sense . I'll back  with updates . Thanks for review .

2023-01-23 21:12 UTC, mfinelli commented
Hi @DataKhukhua are you interested in finishing up the PR? If not, no worries, I'll clean it up and merge it. Thanks for all of your help so far!

2023-03-11 13:19 UTC, mfinelli commented
Squashed, signed, and merged by #19

2023-03-11 13:19 UTC, closed without merging