Feature  edit request editor
mfinelli/cui pull request #17
Opened 2022-10-31 12:18 UTC by DataKhukhua

Works fine . with  vim and neovim ( on my machine :) )

2022-10-31 14:03 UTC, mfinelli commented
Hi, can you please add the GPL copyright notice to the top of any new files that you create? (Same request for your other PR #16)

Could you also please rebase this onto the latest master from my branch? Thanks

2022-10-31 14:04 UTC, DataKhukhua commented
Ofc , I will asap

2022-10-31 14:12 UTC, mfinelli requested changes

2022-10-31 14:12 UTC, mfinelli commented on main.go
> +				editor := os.Getenv("EDITOR")
If `$EDITOR` is empty I think that for now we should just not do anything. I'm working on better error handling which will temporarily (e.g., for 5 seconds or so) replace the instructions status line with the error message so that we don't just panic everywhere. Once I'm finished with that we can update this to tell the user "Hey, you EDITOR env isn't set we don't know what program to open".

2022-10-31 14:12 UTC, mfinelli commented on edit_request_editor.go
> +	tmpFile, errTemp := os.CreateTemp("", tmpFileName)
This is more of a stylistic choice, but can you please name all of the error variables `err` and just reassign them as you progress through the function? This follows the style elsewhere in the code.

2022-10-31 14:12 UTC, mfinelli commented on main.go
> +						return
I would prefer that this panic for now, once the updated error handling is in place we can let the user know what happened but as-is it will just silently fail which isn't a great user experience

2022-10-31 15:16 UTC, jootd commented on main.go
> +				editor := os.Getenv("EDITOR")
I missed that one , thanks for mentioning .

2022-10-31 15:27 UTC, DataKhukhua commented
> 

So, I need to merge master into this branch and commit ,am I right ?

2022-10-31 16:34 UTC, mfinelli commented
It would be better if you rebased on top of master. But if you merge then I think I can still clean it up before I merge to master.

2022-10-31 18:09 UTC, DataKhukhua commented
> tter if you rebased on top of master. But if you merge then I think I can still clean it up before I merge to

Done, but I'm not sure that I did it right way 😌

2022-11-02 12:03 UTC, mfinelli approved these changes

2022-11-02 12:12 UTC, closed without merging

2022-11-02 12:13 UTC, mfinelli commented
Squashed and merged! Thanks!